### ISSUE TITLE
Enable and configure LocalStorage feature

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/k8s-operator#110]
### Enhancement Proposal

Wishlist to support enabling and configuring localstorage feature either via k8s-operator or separate charm

**Comment by ktsakalozos** [comment]
@hemanthnakkina do you want to configure local storage of do you want it enabled by default?

**Comment by hemanthnakkina** [comment]
Currently enabling by default should be sufficient as sunbeam does not update any configuration provided by local storage.

**Comment by mateoflorido** [comment]
Fixed: #169
