### ISSUE TITLE
Support to configure Custom registries

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/k8s-operator#111]
### Enhancement Proposal

Wishlist to configure containerd custom registries

**Comment by addyess** [comment]
Similar to containerd charm's [custom-registries](https://github.com/charmed-kubernetes/charm-containerd/blob/main/config.yaml#L2-L49)

**Comment by mateoflorido** [comment]
@hemanthnakkina This process is documented in the Juju How-To guides under "Configure a Custom Registry" in the Canonical Kubernetes [documentation](https://documentation.ubuntu.com/canonical-kubernetes/main/). It should be avaiable in just a few minutes.
