### ISSUE TITLE
Ability to configure cilium option --vlan-bpf-bypass

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/k8s-operator#112]
### Enhancement Proposal

Cilium failed to start when the primary bond has more than 5 VLANs.
This requires to configure cilium charm --vlan-bpf-bypass option.

[1] https://docs.cilium.io/en/stable/configuration/vlan-802.1q/

**Comment by ktsakalozos** [comment]
@hemanthnakkina do you want to set this option to specific vlans or would a `--vlan-bpf-bypass=0` be good for you (allow all VLAN tags)?

**Comment by hemanthnakkina** [comment]
`--vlan-bpf-bypass=0` should be good as the scenario is primary interface has more than 5 VLANs.
